### ISSUE TITLE
how to config laravel-nuxt project on hosting?

### ISSUE THREAD

**Issue by vakora** [skyrpex/laravel-nuxt#1]
i have laravel ver5.6 and install laravel-nux npm and composer package, but in continue I am so confused
about how implement all of this in my hostin
my hosting support feature:
node : v.9.11.1
npm: 5.6.1
php : 7.1.16

**Comment by skyrpex** [comment]
Hello! I'm not sure what's exactly causing trouble to you. In any case:

* You need to serve your PHP application as usual (using the `public/` path).
* Before that, you'll need to execute the `laravel-nuxt build` command. It'll generate some JS and CSS files under the `public/_nuxt` directory.

That should do it. Feel free to open the issue again if you need further help.
