### ISSUE TITLE
I created a basic template

### ISSUE THREAD

**Issue by yob-yob** [skyrpex/laravel-nuxt#3]
this is just a basic template.

https://gitlab.com/zilex.seryth/Laravel-Nuxt-Template

I've got some few questions thou.
( I don't really know how your service works )

1. are you using php-V8js ?
2. If not ^ , Then how are does this work without running a nuxt server?

sorry for asking questions rather than viewing your repo.. but I've still got no broad knowledge about how nuxt work and how laravel services works. thanks again :)

**Comment by skyrpex** [comment]
Hi there! No worries, I'm happy to help.

> 1. are you using php-V8js ?

Nope, we are not doing anything fancy with PHP.

> 2. If not ^ , Then how are does this work without running a nuxt server?

* In dev mode, a nuxt server is launched (along with the artisan server).
* In production mode, the assets (js, css, html, images...) are compiled in `public/_nuxt` and served as static files.
