### ISSUE TITLE
Support Laravel 5.7

### ISSUE THREAD

**Issue by bionicmaster** [skyrpex/laravel-nuxt#5]
Hi, great job with Laravel-Nuxt, I had started to use it a couple of weeks ago and I love it, the only issue that actually I have is about the support for Laravel 5.7, that doesn't make to upgrade my version to the latest one.

Regards and again, nice job

**Comment by skyrpex** [comment]
Hey, thanks!

Fixed in 86871acdc8a9eee215dea530d116301738578a07, tagged `1.1.0`. Tested it for a while in Laravel 5.7 without any problems.

You should be able to write `composer require pallares/laravel-nuxt` now.
